name: ub4d
channels:
  - pytorch-lts
  - conda-forge
dependencies:
  - python=3.8
  - numpy=1.19
  - cudatoolkit=10.2
  - pytorch=1.8.2
  - torchvision=0.9.2
  - opencv=4.0
  - rtree=0.9
  - tensorboard=2.2
  - trimesh
  - imageio
  - tqdm
  - scipy
  - scikit-learn
  - matplotlib
  - pip=20.2
  - pip:
    - pyhocon
    - pymcubes==0.1
    - pyrender==0.1